<?php
if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * Registry of all 50 VitalHealth Hub calculators.
 * Each entry contains: id, title, slug, category, seo_title,
 * seo_desc, focus_keyword, related (array of other slugs).
 */
function vht_get_calculator_registry() {
    return [
        // ── WEIGHT & BODY ──────────────────────────────────────
        [
            'id'            => 'healthy-weight-range-calculator',
            'title'         => 'Healthy Weight Range Calculator',
            'slug'          => 'healthy-weight-range-calculator',
            'category'      => 'Health Calculators',
            'seo_title'     => 'Healthy Weight Range Calculator — Find Your Ideal Weight | VitalHealth Hub',
            'seo_desc'      => 'Use our free Healthy Weight Range Calculator to find the ideal weight range for your height. Evidence-based results in seconds.',
            'focus_keyword' => 'healthy weight range calculator',
            'related'       => [ 'bmi-calculator', 'body-fat-calculator', 'weight-loss-goal-calculator' ],
        ],
        [
            'id'            => 'weight-loss-goal-calculator',
            'title'         => 'Weight Loss Goal Calculator',
            'slug'          => 'weight-loss-goal-calculator',
            'category'      => 'Health Calculators',
            'seo_title'     => 'Weight Loss Goal Calculator — How Long to Reach Your Target Weight | VitalHealth Hub',
            'seo_desc'      => 'Calculate how long it will take to reach your weight loss goal based on your calorie deficit. Free, instant, evidence-based.',
            'focus_keyword' => 'weight loss goal calculator',
            'related'       => [ 'calorie-deficit-calculator', 'tdee-calculator', 'healthy-weight-range-calculator' ],
        ],
        [
            'id'            => 'weight-gain-calculator',
            'title'         => 'Weight Gain Calculator',
            'slug'          => 'weight-gain-calculator',
            'category'      => 'Health Calculators',
            'seo_title'     => 'Weight Gain Calculator — Calorie Surplus for Muscle and Mass | VitalHealth Hub',
            'seo_desc'      => 'Find your ideal calorie surplus and timeline for healthy weight gain or muscle building. Free weight gain calculator.',
            'focus_keyword' => 'weight gain calculator',
            'related'       => [ 'calorie-calculator', 'protein-intake-calculator', 'macro-calculator' ],
        ],
        [
            'id'            => 'maintenance-calories-calculator',
            'title'         => 'Maintenance Calories Calculator',
            'slug'          => 'maintenance-calories-calculator',
            'category'      => 'Health Calculators',
            'seo_title'     => 'Maintenance Calories Calculator — Your TDEE for Weight Maintenance | VitalHealth Hub',
            'seo_desc'      => 'Calculate your exact maintenance calorie level to keep your current weight stable. Based on the Mifflin-St Jeor equation.',
            'focus_keyword' => 'maintenance calories calculator',
            'related'       => [ 'tdee-calculator', 'bmr-calculator', 'calorie-calculator' ],
        ],
        [
            'id'            => 'meal-calorie-split-calculator',
            'title'         => 'Meal Calorie Split Calculator',
            'slug'          => 'meal-calorie-split-calculator',
            'category'      => 'Nutrition',
            'seo_title'     => 'Meal Calorie Split Calculator — Divide Calories Across Meals | VitalHealth Hub',
            'seo_desc'      => 'Split your daily calorie target across breakfast, lunch, dinner, and snacks with this free meal planner calculator.',
            'focus_keyword' => 'meal calorie split calculator',
            'related'       => [ 'calorie-calculator', 'macro-calculator', 'maintenance-calories-calculator' ],
        ],
        // ── NUTRITION ──────────────────────────────────────────
        [
            'id'            => 'daily-sugar-intake-calculator',
            'title'         => 'Daily Sugar Intake Calculator',
            'slug'          => 'daily-sugar-intake-calculator',
            'category'      => 'Nutrition',
            'seo_title'     => 'Daily Sugar Intake Calculator — How Much Sugar Should You Eat? | VitalHealth Hub',
            'seo_desc'      => 'Find out your recommended daily sugar intake based on age, sex, and health goals. WHO and AHA guidelines applied.',
            'focus_keyword' => 'daily sugar intake calculator',
            'related'       => [ 'calorie-calculator', 'macro-calculator', 'fiber-intake-calculator' ],
        ],
        [
            'id'            => 'sodium-intake-calculator',
            'title'         => 'Sodium Intake Calculator',
            'slug'          => 'sodium-intake-calculator',
            'category'      => 'Nutrition',
            'seo_title'     => 'Sodium Intake Calculator — Daily Salt Limit for Your Health | VitalHealth Hub',
            'seo_desc'      => 'Calculate your daily sodium intake recommendation. Useful for managing blood pressure and heart health.',
            'focus_keyword' => 'sodium intake calculator',
            'related'       => [ 'blood-pressure-checker', 'water-intake-calculator', 'daily-sugar-intake-calculator' ],
        ],
        [
            'id'            => 'potassium-intake-calculator',
            'title'         => 'Potassium Intake Calculator',
            'slug'          => 'potassium-intake-calculator',
            'category'      => 'Nutrition',
            'seo_title'     => 'Potassium Intake Calculator — Daily Potassium Needs | VitalHealth Hub',
            'seo_desc'      => 'Find your daily potassium requirement based on age and sex. Potassium supports heart, kidney, and muscle function.',
            'focus_keyword' => 'potassium intake calculator',
            'related'       => [ 'sodium-intake-calculator', 'magnesium-intake-calculator', 'electrolyte-needs-calculator' ],
        ],
        [
            'id'            => 'magnesium-intake-calculator',
            'title'         => 'Magnesium Intake Calculator',
            'slug'          => 'magnesium-intake-calculator',
            'category'      => 'Nutrition',
            'seo_title'     => 'Magnesium Intake Calculator — Daily Magnesium Needs by Age | VitalHealth Hub',
            'seo_desc'      => 'Calculate how much magnesium you need daily. Magnesium supports sleep, muscle function, and energy production.',
            'focus_keyword' => 'magnesium intake calculator',
            'related'       => [ 'potassium-intake-calculator', 'zinc-intake-calculator', 'sleep-cycle-calculator' ],
        ],
        [
            'id'            => 'zinc-intake-calculator',
            'title'         => 'Zinc Intake Calculator',
            'slug'          => 'zinc-intake-calculator',
            'category'      => 'Nutrition',
            'seo_title'     => 'Zinc Intake Calculator — How Much Zinc Do You Need Daily? | VitalHealth Hub',
            'seo_desc'      => 'Calculate your recommended daily zinc intake for immunity, wound healing, and hormone balance.',
            'focus_keyword' => 'zinc intake calculator',
            'related'       => [ 'magnesium-intake-calculator', 'omega3-intake-calculator', 'protein-intake-calculator' ],
        ],
        [
            'id'            => 'omega3-intake-calculator',
            'title'         => 'Omega-3 Intake Calculator',
            'slug'          => 'omega3-intake-calculator',
            'category'      => 'Nutrition',
            'seo_title'     => 'Omega-3 Intake Calculator — Daily DHA and EPA Needs | VitalHealth Hub',
            'seo_desc'      => 'Find out how much omega-3 (DHA + EPA) you need daily based on your health goals and dietary intake.',
            'focus_keyword' => 'omega-3 intake calculator',
            'related'       => [ 'zinc-intake-calculator', 'fat-intake-calculator', 'heart-health-lifestyle-score' ],
        ],
        [
            'id'            => 'meal-protein-distribution-calculator',
            'title'         => 'Meal Protein Distribution Calculator',
            'slug'          => 'meal-protein-distribution-calculator',
            'category'      => 'Nutrition',
            'seo_title'     => 'Meal Protein Distribution Calculator — Split Protein Across Meals | VitalHealth Hub',
            'seo_desc'      => 'Distribute your daily protein target optimally across meals for maximum muscle protein synthesis.',
            'focus_keyword' => 'protein distribution calculator',
            'related'       => [ 'protein-intake-calculator', 'macro-calculator', 'meal-calorie-split-calculator' ],
        ],
        // ── HYDRATION ──────────────────────────────────────────
        [
            'id'            => 'hydration-by-activity-calculator',
            'title'         => 'Hydration by Activity Calculator',
            'slug'          => 'hydration-by-activity-calculator',
            'category'      => 'Health Calculators',
            'seo_title'     => 'Hydration by Activity Calculator — Water Needs for Exercise | VitalHealth Hub',
            'seo_desc'      => 'Calculate how much extra water you need based on your workout type, intensity, and duration.',
            'focus_keyword' => 'hydration by activity calculator',
            'related'       => [ 'water-intake-calculator', 'electrolyte-needs-calculator', 'kidney-hydration-risk-checker' ],
        ],
        [
            'id'            => 'electrolyte-needs-calculator',
            'title'         => 'Electrolyte Needs Calculator',
            'slug'          => 'electrolyte-needs-calculator',
            'category'      => 'Health Calculators',
            'seo_title'     => 'Electrolyte Needs Calculator — Sodium, Potassium & Magnesium for Exercise | VitalHealth Hub',
            'seo_desc'      => 'Estimate your sodium, potassium, and magnesium needs after exercise to restore electrolyte balance.',
            'focus_keyword' => 'electrolyte needs calculator',
            'related'       => [ 'hydration-by-activity-calculator', 'water-intake-calculator', 'sodium-intake-calculator' ],
        ],
        // ── FITNESS CALORIES ───────────────────────────────────
        [
            'id'            => 'walking-calories-calculator',
            'title'         => 'Walking Calories Calculator',
            'slug'          => 'walking-calories-calculator',
            'category'      => 'Fitness',
            'seo_title'     => 'Walking Calories Calculator — How Many Calories Does Walking Burn? | VitalHealth Hub',
            'seo_desc'      => 'Calculate calories burned walking based on your weight, speed, and distance. Instant, free results.',
            'focus_keyword' => 'walking calories calculator',
            'related'       => [ 'steps-to-calories-calculator', 'hiit-calories-calculator', 'heart-rate-calculator' ],
        ],
        [
            'id'            => 'hiit-calories-calculator',
            'title'         => 'HIIT Calories Calculator',
            'slug'          => 'hiit-calories-calculator',
            'category'      => 'Fitness',
            'seo_title'     => 'HIIT Calories Calculator — How Many Calories Does HIIT Burn? | VitalHealth Hub',
            'seo_desc'      => 'Estimate calories burned during HIIT workouts based on your weight, workout duration, and intensity.',
            'focus_keyword' => 'HIIT calories calculator',
            'related'       => [ 'walking-calories-calculator', 'strength-training-calories-calculator', 'heart-rate-calculator' ],
        ],
        [
            'id'            => 'strength-training-calories-calculator',
            'title'         => 'Strength Training Calories Calculator',
            'slug'          => 'strength-training-calories-calculator',
            'category'      => 'Fitness',
            'seo_title'     => 'Strength Training Calories Calculator — Calories Burned Lifting Weights | VitalHealth Hub',
            'seo_desc'      => 'Calculate how many calories you burn during weight training sessions based on weight, duration, and intensity.',
            'focus_keyword' => 'strength training calories calculator',
            'related'       => [ 'hiit-calories-calculator', 'one-rep-max-calculator', 'protein-intake-calculator' ],
        ],
        [
            'id'            => 'plank-calories-calculator',
            'title'         => 'Plank Calories Calculator',
            'slug'          => 'plank-calories-calculator',
            'category'      => 'Fitness',
            'seo_title'     => 'Plank Calories Calculator — Calories Burned Doing Planks | VitalHealth Hub',
            'seo_desc'      => 'Find out how many calories you burn doing planks based on your weight and hold duration.',
            'focus_keyword' => 'plank calories calculator',
            'related'       => [ 'push-up-calories-calculator', 'squat-calories-calculator', 'walking-calories-calculator' ],
        ],
        [
            'id'            => 'push-up-calories-calculator',
            'title'         => 'Push-Up Calories Calculator',
            'slug'          => 'push-up-calories-calculator',
            'category'      => 'Fitness',
            'seo_title'     => 'Push-Up Calories Calculator — How Many Calories Do Push-Ups Burn? | VitalHealth Hub',
            'seo_desc'      => 'Estimate calories burned doing push-ups based on your weight and number of reps or sets.',
            'focus_keyword' => 'push-up calories calculator',
            'related'       => [ 'plank-calories-calculator', 'squat-calories-calculator', 'strength-training-calories-calculator' ],
        ],
        [
            'id'            => 'squat-calories-calculator',
            'title'         => 'Squat Calories Calculator',
            'slug'          => 'squat-calories-calculator',
            'category'      => 'Fitness',
            'seo_title'     => 'Squat Calories Calculator — Calories Burned Doing Squats | VitalHealth Hub',
            'seo_desc'      => 'Calculate calories burned doing squats based on your body weight and number of repetitions.',
            'focus_keyword' => 'squat calories calculator',
            'related'       => [ 'push-up-calories-calculator', 'plank-calories-calculator', 'hiit-calories-calculator' ],
        ],
        // ── HEART RATE ─────────────────────────────────────────
        [
            'id'            => 'target-heart-rate-zone-calculator',
            'title'         => 'Target Heart Rate Zone Calculator',
            'slug'          => 'target-heart-rate-zone-calculator',
            'category'      => 'Fitness',
            'seo_title'     => 'Target Heart Rate Zone Calculator — Find Your Training Zones | VitalHealth Hub',
            'seo_desc'      => 'Calculate all 5 heart rate training zones from fat burn to VO2 max based on your age and resting heart rate.',
            'focus_keyword' => 'target heart rate zone calculator',
            'related'       => [ 'heart-rate-calculator', 'resting-heart-rate-checker', 'vo2-max-calculator' ],
        ],
        [
            'id'            => 'resting-heart-rate-checker',
            'title'         => 'Resting Heart Rate Checker',
            'slug'          => 'resting-heart-rate-checker',
            'category'      => 'Health Calculators',
            'seo_title'     => 'Resting Heart Rate Checker — Is Your Heart Rate Normal? | VitalHealth Hub',
            'seo_desc'      => 'Check if your resting heart rate is in a healthy range and what it means for your cardiovascular fitness.',
            'focus_keyword' => 'resting heart rate checker',
            'related'       => [ 'target-heart-rate-zone-calculator', 'heart-rate-calculator', 'recovery-heart-rate-calculator' ],
        ],
        [
            'id'            => 'recovery-heart-rate-calculator',
            'title'         => 'Recovery Heart Rate Calculator',
            'slug'          => 'recovery-heart-rate-calculator',
            'category'      => 'Fitness',
            'seo_title'     => 'Recovery Heart Rate Calculator — Heart Rate Recovery After Exercise | VitalHealth Hub',
            'seo_desc'      => 'Calculate your heart rate recovery score after exercise. A key indicator of cardiovascular fitness.',
            'focus_keyword' => 'recovery heart rate calculator',
            'related'       => [ 'resting-heart-rate-checker', 'target-heart-rate-zone-calculator', 'vo2-max-calculator' ],
        ],
        // ── SLEEP ──────────────────────────────────────────────
        [
            'id'            => 'sleep-cycle-calculator',
            'title'         => 'Sleep Cycle Wake-Up Calculator',
            'slug'          => 'sleep-cycle-calculator',
            'category'      => 'Sleep',
            'seo_title'     => 'Sleep Cycle Calculator — Best Times to Wake Up Feeling Rested | VitalHealth Hub',
            'seo_desc'      => 'Enter your bedtime and find the optimal wake-up times aligned with your 90-minute sleep cycles.',
            'focus_keyword' => 'sleep cycle calculator',
            'related'       => [ 'bedtime-calculator', 'nap-time-calculator', 'sleep-calculator' ],
        ],
        [
            'id'            => 'bedtime-calculator',
            'title'         => 'Bedtime Calculator',
            'slug'          => 'bedtime-calculator',
            'category'      => 'Sleep',
            'seo_title'     => 'Bedtime Calculator — What Time Should You Go to Sleep? | VitalHealth Hub',
            'seo_desc'      => 'Enter your wake-up time and find the best bedtime to complete full 90-minute sleep cycles.',
            'focus_keyword' => 'bedtime calculator',
            'related'       => [ 'sleep-cycle-calculator', 'nap-time-calculator', 'sleep-calculator' ],
        ],
        [
            'id'            => 'nap-time-calculator',
            'title'         => 'Nap Time Calculator',
            'slug'          => 'nap-time-calculator',
            'category'      => 'Sleep',
            'seo_title'     => 'Nap Time Calculator — Best Nap Duration for Energy and Focus | VitalHealth Hub',
            'seo_desc'      => 'Find the ideal nap length for energy, focus, or recovery without waking up feeling groggy.',
            'focus_keyword' => 'nap time calculator',
            'related'       => [ 'sleep-cycle-calculator', 'bedtime-calculator', 'stress-recovery-time-calculator' ],
        ],
        // ── MENTAL WELLNESS ────────────────────────────────────
        [
            'id'            => 'screen-time-wellness-calculator',
            'title'         => 'Screen Time Wellness Calculator',
            'slug'          => 'screen-time-wellness-calculator',
            'category'      => 'Mental Wellness',
            'seo_title'     => 'Screen Time Wellness Calculator — How Much Screen Time Is Too Much? | VitalHealth Hub',
            'seo_desc'      => 'Assess your daily screen time and get personalised wellness recommendations to protect sleep, posture, and mental health.',
            'focus_keyword' => 'screen time wellness calculator',
            'related'       => [ 'stress-recovery-time-calculator', 'mindfulness-minutes-calculator', 'posture-risk-calculator' ],
        ],
        [
            'id'            => 'stress-recovery-time-calculator',
            'title'         => 'Stress Recovery Time Calculator',
            'slug'          => 'stress-recovery-time-calculator',
            'category'      => 'Mental Wellness',
            'seo_title'     => 'Stress Recovery Time Calculator — How Long to Recover From Burnout | VitalHealth Hub',
            'seo_desc'      => 'Estimate how much recovery time you need based on your current stress level and lifestyle factors.',
            'focus_keyword' => 'stress recovery time calculator',
            'related'       => [ 'stress-level-calculator', 'mindfulness-minutes-calculator', 'sleep-cycle-calculator' ],
        ],
        [
            'id'            => 'mindfulness-minutes-calculator',
            'title'         => 'Mindfulness Minutes Calculator',
            'slug'          => 'mindfulness-minutes-calculator',
            'category'      => 'Mental Wellness',
            'seo_title'     => 'Mindfulness Minutes Calculator — How Much Meditation Do You Need? | VitalHealth Hub',
            'seo_desc'      => 'Find out how many minutes of mindfulness or meditation per day would benefit your stress level and mental wellbeing.',
            'focus_keyword' => 'mindfulness minutes calculator',
            'related'       => [ 'stress-recovery-time-calculator', 'stress-level-calculator', 'work-life-balance-score-calculator' ],
        ],
        [
            'id'            => 'work-life-balance-score-calculator',
            'title'         => 'Work-Life Balance Score Calculator',
            'slug'          => 'work-life-balance-score-calculator',
            'category'      => 'Mental Wellness',
            'seo_title'     => 'Work-Life Balance Score Calculator — Rate Your Work-Life Balance | VitalHealth Hub',
            'seo_desc'      => 'Answer 10 quick questions to score your current work-life balance and get personalised improvement tips.',
            'focus_keyword' => 'work-life balance calculator',
            'related'       => [ 'mindfulness-minutes-calculator', 'stress-recovery-time-calculator', 'screen-time-wellness-calculator' ],
        ],
        // ── POSTURE & LIFESTYLE ────────────────────────────────
        [
            'id'            => 'posture-risk-calculator',
            'title'         => 'Posture Risk Calculator',
            'slug'          => 'posture-risk-calculator',
            'category'      => 'Lifestyle',
            'seo_title'     => 'Posture Risk Calculator — Are You at Risk of Poor Posture Problems? | VitalHealth Hub',
            'seo_desc'      => 'Assess your posture risk based on sitting hours, screen time, and activity level. Get actionable recommendations.',
            'focus_keyword' => 'posture risk calculator',
            'related'       => [ 'desk-break-reminder-calculator', 'screen-time-wellness-calculator', 'walking-calories-calculator' ],
        ],
        [
            'id'            => 'desk-break-reminder-calculator',
            'title'         => 'Desk Break Reminder Calculator',
            'slug'          => 'desk-break-reminder-calculator',
            'category'      => 'Lifestyle',
            'seo_title'     => 'Desk Break Reminder Calculator — How Often Should You Take Breaks? | VitalHealth Hub',
            'seo_desc'      => 'Find the ideal frequency and duration of desk breaks to protect your posture, circulation, and productivity.',
            'focus_keyword' => 'desk break calculator',
            'related'       => [ 'posture-risk-calculator', 'screen-time-wellness-calculator', 'work-life-balance-score-calculator' ],
        ],
        // ── PREGNANCY & BABY ───────────────────────────────────
        [
            'id'            => 'pregnancy-weight-gain-calculator',
            'title'         => 'Pregnancy Weight Gain Calculator',
            'slug'          => 'pregnancy-weight-gain-calculator',
            'category'      => 'Pregnancy & Baby',
            'seo_title'     => 'Pregnancy Weight Gain Calculator — Healthy Weight Gain During Pregnancy | VitalHealth Hub',
            'seo_desc'      => 'Calculate healthy weight gain during pregnancy based on your pre-pregnancy BMI and trimester. Based on IOM guidelines.',
            'focus_keyword' => 'pregnancy weight gain calculator',
            'related'       => [ 'fertile-window-calculator', 'bmi-calculator', 'water-intake-calculator' ],
        ],
        [
            'id'            => 'baby-feeding-amount-calculator',
            'title'         => 'Baby Feeding Amount Calculator',
            'slug'          => 'baby-feeding-amount-calculator',
            'category'      => 'Pregnancy & Baby',
            'seo_title'     => 'Baby Feeding Amount Calculator — How Much Should Your Baby Eat? | VitalHealth Hub',
            'seo_desc'      => 'Calculate how much breast milk or formula your baby needs per feeding and per day based on age and weight.',
            'focus_keyword' => 'baby feeding amount calculator',
            'related'       => [ 'baby-sleep-needs-calculator', 'baby-growth-percentile-helper', 'pregnancy-weight-gain-calculator' ],
        ],
        [
            'id'            => 'baby-sleep-needs-calculator',
            'title'         => 'Baby Sleep Needs Calculator',
            'slug'          => 'baby-sleep-needs-calculator',
            'category'      => 'Pregnancy & Baby',
            'seo_title'     => 'Baby Sleep Needs Calculator — How Much Sleep Does Your Baby Need? | VitalHealth Hub',
            'seo_desc'      => 'Find the recommended sleep duration for your baby or toddler by age, based on AAP and NHS guidelines.',
            'focus_keyword' => 'baby sleep needs calculator',
            'related'       => [ 'baby-feeding-amount-calculator', 'baby-growth-percentile-helper', 'sleep-cycle-calculator' ],
        ],
        [
            'id'            => 'baby-growth-percentile-helper',
            'title'         => 'Baby Growth Percentile Helper',
            'slug'          => 'baby-growth-percentile-helper',
            'category'      => 'Pregnancy & Baby',
            'seo_title'     => 'Baby Growth Percentile Helper — Is Your Baby Growing Normally? | VitalHealth Hub',
            'seo_desc'      => 'Check your baby\'s weight and height percentile using WHO growth charts. Understand if your child is growing on track.',
            'focus_keyword' => 'baby growth percentile calculator',
            'related'       => [ 'baby-feeding-amount-calculator', 'baby-sleep-needs-calculator', 'child-bmi-calculator' ],
        ],
        [
            'id'            => 'fertile-window-calculator',
            'title'         => 'Fertile Window Calculator',
            'slug'          => 'fertile-window-calculator',
            'category'      => 'Pregnancy & Baby',
            'seo_title'     => 'Fertile Window Calculator — When Are You Most Fertile? | VitalHealth Hub',
            'seo_desc'      => 'Find your fertile window and most likely ovulation day based on your cycle length and last period date.',
            'focus_keyword' => 'fertile window calculator',
            'related'       => [ 'period-length-calculator', 'pms-symptom-tracker', 'pregnancy-weight-gain-calculator' ],
        ],
        [
            'id'            => 'period-length-calculator',
            'title'         => 'Period Length Calculator',
            'slug'          => 'period-length-calculator',
            'category'      => 'Pregnancy & Baby',
            'seo_title'     => 'Period Length Calculator — Track Your Menstrual Cycle Length | VitalHealth Hub',
            'seo_desc'      => 'Track your menstrual cycle length and predict your next period date with our free period length calculator.',
            'focus_keyword' => 'period length calculator',
            'related'       => [ 'fertile-window-calculator', 'pms-symptom-tracker', 'menopause-symptom-score-calculator' ],
        ],
        [
            'id'            => 'pms-symptom-tracker',
            'title'         => 'PMS Symptom Tracker Calculator',
            'slug'          => 'pms-symptom-tracker',
            'category'      => 'Pregnancy & Baby',
            'seo_title'     => 'PMS Symptom Tracker — Rate Your PMS Symptoms | VitalHealth Hub',
            'seo_desc'      => 'Log and score your premenstrual symptoms to understand your PMS severity and get lifestyle management tips.',
            'focus_keyword' => 'PMS symptom tracker',
            'related'       => [ 'period-length-calculator', 'fertile-window-calculator', 'menopause-symptom-score-calculator' ],
        ],
        [
            'id'            => 'menopause-symptom-score-calculator',
            'title'         => 'Menopause Symptom Score Calculator',
            'slug'          => 'menopause-symptom-score-calculator',
            'category'      => 'Pregnancy & Baby',
            'seo_title'     => 'Menopause Symptom Score Calculator — Rate Your Menopause Symptoms | VitalHealth Hub',
            'seo_desc'      => 'Score your menopause symptoms using the validated Greene Climacteric Scale and receive guidance on management.',
            'focus_keyword' => 'menopause symptom score calculator',
            'related'       => [ 'pms-symptom-tracker', 'stress-recovery-time-calculator', 'sleep-cycle-calculator' ],
        ],
        // ── PREVENTIVE HEALTH ──────────────────────────────────
        [
            'id'            => 'waist-circumference-risk-checker',
            'title'         => 'Waist Circumference Risk Checker',
            'slug'          => 'waist-circumference-risk-checker',
            'category'      => 'Preventive Health',
            'seo_title'     => 'Waist Circumference Risk Checker — Is Your Waist Size Healthy? | VitalHealth Hub',
            'seo_desc'      => 'Check if your waist circumference puts you at risk for heart disease, diabetes, or metabolic syndrome.',
            'focus_keyword' => 'waist circumference risk checker',
            'related'       => [ 'waist-to-hip-ratio', 'bmi-calculator', 'body-fat-calculator' ],
        ],
        [
            'id'            => 'metabolic-age-calculator',
            'title'         => 'Metabolic Age Calculator',
            'slug'          => 'metabolic-age-calculator',
            'category'      => 'Preventive Health',
            'seo_title'     => 'Metabolic Age Calculator — Is Your Body Older or Younger Than Your Age? | VitalHealth Hub',
            'seo_desc'      => 'Estimate your metabolic age based on your BMR compared to average BMR for your chronological age group.',
            'focus_keyword' => 'metabolic age calculator',
            'related'       => [ 'bmr-calculator', 'body-fat-calculator', 'tdee-calculator' ],
        ],
        [
            'id'            => 'insulin-resistance-risk-estimator',
            'title'         => 'Insulin Resistance Risk Estimator',
            'slug'          => 'insulin-resistance-risk-estimator',
            'category'      => 'Preventive Health',
            'seo_title'     => 'Insulin Resistance Risk Estimator — Are You at Risk? | VitalHealth Hub',
            'seo_desc'      => 'Estimate your risk of insulin resistance based on lifestyle factors, waist size, and activity level.',
            'focus_keyword' => 'insulin resistance risk calculator',
            'related'       => [ 'waist-circumference-risk-checker', 'metabolic-age-calculator', 'daily-sugar-intake-calculator' ],
        ],
        [
            'id'            => 'family-health-risk-score-calculator',
            'title'         => 'Family Health Risk Score Calculator',
            'slug'          => 'family-health-risk-score-calculator',
            'category'      => 'Preventive Health',
            'seo_title'     => 'Family Health Risk Score Calculator — Genetic Risk Assessment | VitalHealth Hub',
            'seo_desc'      => 'Assess your genetic health risk based on family history of heart disease, diabetes, cancer, and stroke.',
            'focus_keyword' => 'family health risk calculator',
            'related'       => [ 'insulin-resistance-risk-estimator', 'heart-health-lifestyle-score', 'waist-circumference-risk-checker' ],
        ],
        [
            'id'            => 'heart-health-lifestyle-score',
            'title'         => 'Heart Health Lifestyle Score',
            'slug'          => 'heart-health-lifestyle-score',
            'category'      => 'Preventive Health',
            'seo_title'     => 'Heart Health Lifestyle Score — Rate Your Heart Health Habits | VitalHealth Hub',
            'seo_desc'      => 'Score your heart health across diet, exercise, smoking, stress, and sleep. Get a personalised action plan.',
            'focus_keyword' => 'heart health lifestyle score',
            'related'       => [ 'blood-pressure-checker', 'heart-rate-calculator', 'family-health-risk-score-calculator' ],
        ],
        [
            'id'            => 'liver-health-lifestyle-score',
            'title'         => 'Liver Health Lifestyle Score',
            'slug'          => 'liver-health-lifestyle-score',
            'category'      => 'Preventive Health',
            'seo_title'     => 'Liver Health Lifestyle Score — Is Your Lifestyle Good for Your Liver? | VitalHealth Hub',
            'seo_desc'      => 'Evaluate your liver health risk based on alcohol intake, diet quality, activity level, and weight.',
            'focus_keyword' => 'liver health lifestyle score',
            'related'       => [ 'alcohol-calorie-calculator', 'heart-health-lifestyle-score', 'insulin-resistance-risk-estimator' ],
        ],
        [
            'id'            => 'kidney-hydration-risk-checker',
            'title'         => 'Kidney Hydration Risk Checker',
            'slug'          => 'kidney-hydration-risk-checker',
            'category'      => 'Preventive Health',
            'seo_title'     => 'Kidney Hydration Risk Checker — Is Dehydration Putting Your Kidneys at Risk? | VitalHealth Hub',
            'seo_desc'      => 'Assess your kidney hydration risk based on daily water intake, urine colour, and fluid loss factors.',
            'focus_keyword' => 'kidney hydration risk checker',
            'related'       => [ 'water-intake-calculator', 'hydration-by-activity-calculator', 'electrolyte-needs-calculator' ],
        ],
        // ── LIFESTYLE ──────────────────────────────────────────
        [
            'id'            => 'alcohol-calorie-calculator',
            'title'         => 'Alcohol Calorie Calculator',
            'slug'          => 'alcohol-calorie-calculator',
            'category'      => 'Lifestyle',
            'seo_title'     => 'Alcohol Calorie Calculator — How Many Calories Are in Your Drinks? | VitalHealth Hub',
            'seo_desc'      => 'Calculate the calories in beer, wine, and spirits and see how they fit into your daily calorie budget.',
            'focus_keyword' => 'alcohol calorie calculator',
            'related'       => [ 'calorie-calculator', 'liver-health-lifestyle-score', 'nicotine-savings-calculator' ],
        ],
        [
            'id'            => 'nicotine-savings-calculator',
            'title'         => 'Nicotine Savings Calculator',
            'slug'          => 'nicotine-savings-calculator',
            'category'      => 'Lifestyle',
            'seo_title'     => 'Nicotine Savings Calculator — How Much Money Will You Save by Quitting? | VitalHealth Hub',
            'seo_desc'      => 'Calculate how much money you will save by quitting smoking based on your daily cigarette consumption and price.',
            'focus_keyword' => 'nicotine savings calculator',
            'related'       => [ 'alcohol-calorie-calculator', 'heart-health-lifestyle-score', 'liver-health-lifestyle-score' ],
        ],
        [
            'id'            => 'wellness-score-calculator',
            'title'         => 'Wellness Score Calculator',
            'slug'          => 'wellness-score-calculator',
            'category'      => 'Health Calculators',
            'seo_title'     => 'Wellness Score Calculator — Rate Your Overall Health and Wellbeing | VitalHealth Hub',
            'seo_desc'      => 'Get your overall wellness score across nutrition, sleep, activity, stress, and mental health. Free, instant results.',
            'focus_keyword' => 'wellness score calculator',
            'related'       => [ 'work-life-balance-score-calculator', 'heart-health-lifestyle-score', 'stress-level-calculator' ],
        ],
    ];
}
